services:

  # This is a subGHz link to both end-devices and relay gateways
  chirpstack-concentratord-slot1:
    
    container_name: chirpstack-concentratord-slot1
    image: xoseperez/chirpstack-concentratord
    restart: unless-stopped
    devices:
      - /dev/ttyACM0
    #  - /dev/spidev0.0
    #  - /dev/gpiochip0
    volumes:
      - ipcfolder:/tmp
    environment:
      DEBUG: "INFO"
      MODEL: "RAK7271"
      INTERFACE: "USB"
      REGION: "eu868"
      SOCKET_NAME: "slot1"
    #group_add:
    #  - ${PGID_GPIO:-993}
    #  - ${PGID_I2C:-994}
    #  - ${PGID_SPI:-995}

  # The gateway-relay service relays message from end devices 
  # to other gateways using the same concentrator
  chirpstack-gateway-relay:
    
    container_name: chirpstack-gateway-relay
    image: xoseperez/chirpstack-gateway-relay
    restart: unless-stopped
    depends_on:
      - chirpstack-concentratord-slot1
    volumes:
      - ipcfolder:/tmp
    environment:
      LOGGING_LEVEL: "INFO"
      RELAY_BORDER: "false"
      RELAY_IGNORE_DIRECT: "false"
      RELAY_REGION: "eu868"
      RELAY_TX_POWER: 16
      RELAY_SOCKET_DEVICES: "slot1"
      RELAY_SOCKET_RELAY: "slot1"

volumes:
  ipcfolder: