services:

  # This is a subGHz link to both end-devices and relay gateways
  chirpstack-concentratord-slot1:
    
    container_name: chirpstack-concentratord-slot1
    image: xoseperez/chirpstack-concentratord
    restart: unless-stopped
    privileged: true
    volumes:
      - /tmp:/tmp
    environment:
      DEBUG: "INFO"
      MODEL: "RAK5146"
      INTERFACE: "SPI"
      RESET_GPIO: 17
      REGION: "eu868"
      SOCKER_NAME: "slot1"

  # The gateway-relay service relays message from end devices 
  # to other gateways using the same concentrator
  chirpstack-gateway-relay:
    
    container_name: chirpstack-gateway-relay
    image: xoseperez/chirpstack-gateway-relay
    restart: unless-stopped
    privileged: true
    depends_on:
      - chirpstack-concentratord-slot1
    volumes:
      - /tmp:/tmp
    environment:
      LOGGING_LEVEL: "INFO"
      RELAY_BORDER: "false"
      RELAY_IGNORE_DIRECT: "false"
      RELAY_REGION: "eu868"
      RELAY_TX_POWER: 16
      RELAY_SOCKET_DEVICES: "slot1"
      RELAY_SOCKET_RELAY: "slot1"
