#!/bin/bash

# -----------------------------------------------------------------------------
# Colors
# -----------------------------------------------------------------------------

COLOR_INFO="\e[32m" # green
COLOR_RESET="\e[0m"

# -----------------------------------------------------------------------------
# Utils
# -----------------------------------------------------------------------------

replace_placeholder() {

    FILE="$1"
    NAME="$2"
    VALUE="$3"

    sed 's|{{'"${NAME}"'}}|'"${VALUE}"'|g' -i "${FILE}"

}

declare -A FREQUENCIES=(
    [eu868]="868100000,868300000,868500000"
    [us915]="902300000,902500000,902700000"
    [ism2400]="2403000000,2479000000,2425000000"
)

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

LOGGING_LEVEL=${LOGGING_LEVEL:-"INFO"}
RELAY_BORDER=${RELAY_BORDER:-"false"}
[[ "${RELAY_BORDER}" == "true" ]] && RELAY_IGNORE_DIRECT=${RELAY_IGNORE_DIRECT:-"false"} || RELAY_IGNORE_DIRECT="false"

RELAY_REGION_DEVICES=${RELAY_REGION_DEVICES,,:-"eu868"}
RELAY_REGION_RELAY=${RELAY_REGION_RELAY,,:-"eu868"}
RELAY_FREQUENCIES=${RELAY_FREQUENCIES:-${FREQUENCIES[${RELAY_REGION_RELAY}]}}
if [[ "${RELAY_REGION_RELAY}" == "ism2400" ]]; then
    RELAY_TX_POWER=${RELAY_TX_POWER:-10}
else
    RELAY_TX_POWER=${RELAY_TX_POWER:-16}
fi
RELAY_MODULATION=${RELAY_MODULATION:-"LORA"}
RELAY_SF=${RELAY_SF:-7}
RELAY_BANDWIDTH=${RELAY_BANDWIDTH:-125000}
RELAY_CODERATE=${RELAY_CODERATE:-"4/5"}
RELAY_FSK_BITRATE=${RELAY_FSK_BITRATE:-0}

RELAY_SOCKET_DEVICES=${RELAY_SOCKET_DEVICES:-"concentratord"}
RELAY_SOCKET_RELAY=${RELAY_SOCKET_RELAY:-"concentratord"}
RELAY_SOCKET_FORWARDER=${RELAY_SOCKET_FORWARDER:-"forwarder"}

# -----------------------------------------------------------------------------
# Check
# -----------------------------------------------------------------------------

if [[ ! -f "./region_${RELAY_REGION_DEVICES}.toml" ]]; then
    echo "Unknown region ${RELAY_REGION_DEVICES}, you must set a valid RELAY_REGION_DEVICES"
    sleep 5
    exit 1
fi

if [[ -z "${RELAY_FREQUENCIES}" ]]; then
    echo "You must set either a valid RELAY_REGION_RELAY or a list of RELAY_FREQUENCIES"
    sleep 5
    exit 1
fi 

# -----------------------------------------------------------------------------
# Build configuration
# -----------------------------------------------------------------------------

CONFIG_FILE=./config.toml

# Copy template
cp chirpstack-gateway-relay.toml.template "${CONFIG_FILE}"

# Replace values
replace_placeholder "${CONFIG_FILE}" "LOGGING_LEVEL" "${LOGGING_LEVEL}"
replace_placeholder "${CONFIG_FILE}" "RELAY_BORDER" "${RELAY_BORDER}"
replace_placeholder "${CONFIG_FILE}" "RELAY_IGNORE_DIRECT" "${RELAY_IGNORE_DIRECT}"
replace_placeholder "${CONFIG_FILE}" "RELAY_FREQUENCIES" "${RELAY_FREQUENCIES}"
replace_placeholder "${CONFIG_FILE}" "RELAY_TX_POWER" "${RELAY_TX_POWER}"
replace_placeholder "${CONFIG_FILE}" "RELAY_MODULATION" "${RELAY_MODULATION}"
replace_placeholder "${CONFIG_FILE}" "RELAY_SF" "${RELAY_SF}"
replace_placeholder "${CONFIG_FILE}" "RELAY_BANDWIDTH" "${RELAY_BANDWIDTH}"
replace_placeholder "${CONFIG_FILE}" "RELAY_CODERATE" "${RELAY_CODERATE}"
replace_placeholder "${CONFIG_FILE}" "RELAY_FSK_BITRATE" "${RELAY_FSK_BITRATE}"
replace_placeholder "${CONFIG_FILE}" "RELAY_SOCKET_FORWARDER" "${RELAY_SOCKET_FORWARDER}"
replace_placeholder "${CONFIG_FILE}" "RELAY_SOCKET_DEVICES" "${RELAY_SOCKET_DEVICES}"
replace_placeholder "${CONFIG_FILE}" "RELAY_SOCKET_RELAY" "${RELAY_SOCKET_RELAY}"

# -----------------------------------------------------------------------------
# Info
# -----------------------------------------------------------------------------

echo
echo -e "${COLOR_INFO}------------------------------------------------------------------"
echo -e "${COLOR_INFO}$( ./chirpstack-gateway-relay -V )"
echo -e "${COLOR_INFO}LoRa(WAN) Gateway Relay Service"
echo -e "${COLOR_INFO}------------------------------------------------------------------"
echo -e "${COLOR_INFO}Logging level:             ${LOGGING_LEVEL}"
echo -e "${COLOR_INFO}Border gateway:            ${RELAY_BORDER}"
echo -e "${COLOR_INFO}Ignore direct messages:    ${RELAY_IGNORE_DIRECT}"
echo -e "${COLOR_INFO}Relaying for:              ${RELAY_REGION_DEVICES}"
echo -e "${COLOR_INFO}Relay frequences:          ${RELAY_FREQUENCIES}"
echo -e "${COLOR_INFO}Relay TX power:            ${RELAY_TX_POWER}"
echo -e "${COLOR_INFO}Relay modulation:          ${RELAY_MODULATION}"
if [[ "${RELAY_MODULATION}" == "LORA" ]]; then
echo -e "${COLOR_INFO}Relay spreading factor:    ${RELAY_SF}"
echo -e "${COLOR_INFO}Relay bandwidth:           ${RELAY_BANDWIDTH}"
echo -e "${COLOR_INFO}Relay code-rate:           ${RELAY_CODERATE}"
else
echo -e "${COLOR_INFO}Relay bitrate:             ${RELAY_FSK_BITRATE}"
fi
echo -e "${COLOR_INFO}End-device socket name:    ${RELAY_SOCKET_DEVICES}"
echo -e "${COLOR_INFO}Relay socket name:         ${RELAY_SOCKET_RELAY}"
if [[ "${RELAY_BORDER}" == "true" ]]; then
echo -e "${COLOR_INFO}Forwarder socket name:     ${RELAY_SOCKET_FORWARDER}"
fi
echo -e "${COLOR_INFO}------------------------------------------------------------------"
echo -e "${COLOR_INFO}Resources: https://www.chirpstack.io/docs/chirpstack-gateway-relay"
echo -e "${COLOR_INFO}           https://github.com/chirpstack/chirpstack-gateway-relay"
echo -e "${COLOR_INFO}------------------------------------------------------------------"
echo -e "${COLOR_RESET}"

# -----------------------------------------------------------------------------
# Manage sockets
# -----------------------------------------------------------------------------

if [[ "${RELAY_BORDER}" == "true" ]]; then
    rm -rf "/tmp/${RELAY_SOCKET_FORWARDER}_event"
    rm -rf "/tmp/${RELAY_SOCKET_FORWARDER}_command"
fi

sleep 2

while [[ ! -S "/tmp/${RELAY_SOCKET_DEVICES}_event" ]]; do sleep 1; done
while [[ ! -S "/tmp/${RELAY_SOCKET_RELAY}_event" ]]; do sleep 1; done

# -----------------------------------------------------------------------------
# Start gateway-relay
# -----------------------------------------------------------------------------
./chirpstack-gateway-relay -c "${CONFIG_FILE}" -c "./region_${RELAY_REGION_DEVICES}.toml"
